### ISSUE TITLE
Hello Gremioc12.

### ISSUE THREAD

**Issue by aaronwayas** [Guildc12/bloxfruitsStockBot#3]
### Help

I liked all the code of your project about Blox Fruits stock. Thanks to your code, I was able to get an idea about discord.py. I have tried to do something similar, although it didn't turn out very well. I have noticed that the stock has changed at "https://blox-fruits.fandom.com/wiki/Blox_Fruits_%22Stock%22" and the !stock command is not working correctly. I don't know much about it. Do you have any ideas on how to solve that? Thank you.

**Comment by WillowWillo** [comment]
Sure, I do. However, the errors are in BloxM.py. The web scraping isn't working anymore because the stock has changed, but it should be patched soon.
